// This file is auto-generated by AI agent
import React from 'react';
import './BugPage.css';

const BugPage: React.FC = () => {
  const handlePress = () => {
    // Bug: 'aler' instead of 'alert' - this will cause a ReferenceError
    aler("Success!");
  };

  return (
    <div className="bug-page">
      <h1>Bug Page</h1>
      <p>This page contains a deliberate bug. Click the button to see what happens.</p>
      <button onClick={handlePress}>Press me</button>
    </div>
  );
};

export default BugPage;