// This file is auto-generated by AI agent
import { render, screen, waitFor, fireEvent } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { QuestionnaireForm } from './QuestionnaireForm';

// Mock the API service
jest.mock('../services/api');
import { apiService } from '../services/api';

const mockApiService = apiService as jest.Mocked<typeof apiService>;

describe('QuestionnaireForm', () => {
  beforeEach(() => {
    mockApiService.getQuestions.mockResolvedValue([
      { id: '1', text: 'What is your favorite language?', type: 'single', options: ['Python', 'Java'] },
    ]);
    mockApiService.submitAnswers.mockResolvedValue({});
  });

  test('loads and displays questions', async () => {
    render(<QuestionnaireForm />);
    await waitFor(() => {
      expect(screen.getByText('What is your favorite language?')).toBeInTheDocument();
    });
  });

  test('submits answers successfully', async () => {
    const user = userEvent.setup();
    render(<QuestionnaireForm />);

    await waitFor(() => {
      expect(screen.getByText('What is your favorite language?')).toBeInTheDocument();
    });

    // Select an answer
    const select = screen.getByRole('combobox');
    await user.selectOptions(select, 'Python');

    // Submit
    const submitButton = screen.getByRole('button', { name: /submit/i });
    await user.click(submitButton);

    await waitFor(() => {
      expect(mockApiService.submitAnswers).toHaveBeenCalledWith({
        answers: [{ question_id: '1', answer: 'Python' }],
      });
    });
  });
});