// This file is auto-generated by AI agent
import React from 'react';
import { render, screen, waitFor } from '@testing-library/react';
import '@testing-library/jest-dom';
import StatisticsPage from './StatisticsPage';
import { apiService } from '../services/api';

// Mock the API service
jest.mock('../services/api');
const mockApiService = apiService as jest.Mocked<typeof apiService>;

describe('StatisticsPage', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  test('renders loading state initially', () => {
    mockApiService.getStatistics.mockImplementation(() => new Promise(() => {})); // Never resolves

    render(<StatisticsPage />);

    expect(screen.getByText('Loading statistics...')).toBeInTheDocument();
  });

  test('renders statistics successfully', async () => {
    mockApiService.getStatistics.mockResolvedValue({ total_submitted: 42 });

    render(<StatisticsPage />);

    await waitFor(() => {
      expect(screen.getByText('Questionnaire Statistics')).toBeInTheDocument();
    });

    expect(screen.getByText('42')).toBeInTheDocument();
    expect(screen.getByText('Total Questionnaires Submitted')).toBeInTheDocument();
  });

  test('renders error state on API failure', async () => {
    mockApiService.getStatistics.mockRejectedValue(new Error('Network error'));

    render(<StatisticsPage />);

    await waitFor(() => {
      expect(screen.getByText('Error loading statistics')).toBeInTheDocument();
    });

    expect(screen.getByText('Network error')).toBeInTheDocument();
    expect(screen.getByText('Retry')).toBeInTheDocument();
  });

  test('has green background styling', () => {
    mockApiService.getStatistics.mockImplementation(() => new Promise(() => {}));

    render(<StatisticsPage />);

    const container = screen.getByText('Loading statistics...').closest('div');
    expect(container).toHaveStyle({ backgroundColor: '#22c55e' });
  });
});