// This file is auto-generated by AI agent
import React, { useState, useEffect } from 'react';
import { apiService } from '../services/api';

interface Statistics {
  total_submitted: number;
}

const StatisticsPage: React.FC = () => {
  const [stats, setStats] = useState<Statistics | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const loadStats = async () => {
      try {
        const data = await apiService.getStatistics();
        setStats(data);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to load statistics');
      } finally {
        setLoading(false);
      }
    };

    loadStats();
  }, []);

  if (loading) {
    return (
      <div style={{
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        height: '100vh',
        backgroundColor: '#22c55e', // green background
        color: 'white'
      }}>
        <h2>Loading statistics...</h2>
      </div>
    );
  }

  if (error) {
    return (
      <div style={{
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        height: '100vh',
        backgroundColor: '#22c55e', // green background
        color: 'white'
      }}>
        <h2>Error loading statistics</h2>
        <p>{error}</p>
        <button
          onClick={() => window.location.reload()}
          style={{
            marginTop: '1rem',
            padding: '0.5rem 1rem',
            backgroundColor: 'white',
            color: '#22c55e',
            border: 'none',
            borderRadius: '4px',
            cursor: 'pointer'
          }}
        >
          Retry
        </button>
      </div>
    );
  }

  return (
    <div style={{
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      height: '100vh',
      backgroundColor: '#22c55e', // green background
      color: 'white'
    }}>
      <h1>Questionnaire Statistics</h1>
      <div style={{
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        padding: '2rem',
        borderRadius: '8px',
        textAlign: 'center'
      }}>
        <h2>Total Questionnaires Submitted</h2>
        <p style={{ fontSize: '3rem', fontWeight: 'bold' }}>
          {stats?.total_submitted || 0}
        </p>
      </div>
      <button
        onClick={() => window.history.back()}
        style={{
          marginTop: '2rem',
          padding: '0.75rem 1.5rem',
          backgroundColor: 'white',
          color: '#22c55e',
          border: 'none',
          borderRadius: '4px',
          cursor: 'pointer',
          fontSize: '1rem'
        }}
      >
        Back to Home
      </button>
    </div>
  );
};

export default StatisticsPage;