# This file is auto-generated by AI agent
"""Tests for repositories.py."""
import pytest
import json
import os
import tempfile
from unittest.mock import patch
from src.infrastructure.repositories import JsonQuestionRepository, JsonAnswerRepository
from src.domain.models import Question, Answer


def test_json_question_repository_get_all_questions():
    """Test JsonQuestionRepository.get_all_questions."""
    # Create a temporary JSON file
    questions_data = {
        "questions": [
            {"id": "1", "text": "Test?", "type": "single", "options": ["A", "B"]}
        ]
    }
    with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
        json.dump(questions_data, f)
        temp_path = f.name

    try:
        repo = JsonQuestionRepository(temp_path)
        questions = repo.get_all_questions()
        assert len(questions) == 1
        assert questions[0].id == "1"
        assert questions[0].text == "Test?"
    finally:
        os.unlink(temp_path)


def test_json_answer_repository_save_answers():
    """Test JsonAnswerRepository.save_answers."""
    with tempfile.TemporaryDirectory() as temp_dir:
        repo = JsonAnswerRepository(temp_dir)
        answers = [Answer(question_id="1", answer="A")]
        repo.save_answers(answers)
        # Check if file was created
        files = os.listdir(temp_dir)
        assert len(files) >= 1  # count.txt and at least one answer file
        # Check count.txt
        count_file = os.path.join(temp_dir, "count.txt")
        with open(count_file, 'r') as f:
            assert f.read().strip() == "1"


def test_json_answer_repository_get_all_answers():
    """Test JsonAnswerRepository.get_all_answers."""
    with tempfile.TemporaryDirectory() as temp_dir:
        # Create count.txt
        with open(os.path.join(temp_dir, "count.txt"), 'w') as f:
            f.write("1")
        # Create a sample answer file with correct naming
        sample_data = [{"question_id": "1", "answer": "A"}]
        with open(os.path.join(temp_dir, "Answers_1_20260205_003143.json"), 'w') as f:
            json.dump(sample_data, f)

        repo = JsonAnswerRepository(temp_dir)
        answers = repo.get_all_answers()
        assert len(answers) == 1
        assert answers[0].question_id == "1"


def test_json_answer_repository_get_submitted_count():
    """Test JsonAnswerRepository.get_submitted_count."""
    with tempfile.TemporaryDirectory() as temp_dir:
        repo = JsonAnswerRepository(temp_dir)
        # Initially 0
        assert repo.get_submitted_count() == 0
        # After saving
        answers = [Answer(question_id="1", answer="A")]
        repo.save_answers(answers)
        assert repo.get_submitted_count() == 1