# This file is auto-generated by AI agent
"""Tests for services.py."""
import pytest
from unittest.mock import Mock
from src.application.services import QuestionService, AnswerService
from src.domain.models import Question, Answer


def test_question_service_get_all_questions():
    """Test QuestionService.get_questions."""
    mock_repo = Mock()
    mock_repo.get_all_questions.return_value = [
        Question(id="1", text="Test?", type="single", options=["A", "B"])
    ]
    service = QuestionService(mock_repo)
    questions = service.get_questions()
    assert len(questions) == 1
    assert questions[0].id == "1"
    mock_repo.get_all_questions.assert_called_once()


def test_answer_service_save_answers():
    """Test AnswerService.submit_answers."""
    mock_repo = Mock()
    service = AnswerService(mock_repo)
    answers = [Answer(question_id="1", answer="A")]
    service.submit_answers(answers)
    mock_repo.save_answers.assert_called_once_with(answers)


def test_answer_service_get_submitted_count():
    """Test AnswerService.get_submitted_count."""
    mock_repo = Mock()
    mock_repo.get_submitted_count.return_value = 5
    service = AnswerService(mock_repo)
    count = service.get_submitted_count()
    assert count == 5
    mock_repo.get_submitted_count.assert_called_once()