# This file is auto-generated by AI agent
"""Tests for routes.py."""
import pytest
from unittest.mock import Mock
from fastapi.testclient import TestClient
from src.app import create_app
from src.presentation.routes import set_services
from src.domain.models import Question, Answer


@pytest.fixture
def mock_question_service():
    """Mock question service."""
    service = Mock()
    service.get_questions.return_value = [
        Question(id="1", text="What is your favorite language?", type="single", options=["Python", "Java"])
    ]
    return service


@pytest.fixture
def mock_answer_service():
    """Mock answer service."""
    service = Mock()
    return service


@pytest.fixture
def client(mock_question_service, mock_answer_service):
    """Create a test client with mocked services."""
    app = create_app()
    set_services(mock_question_service, mock_answer_service)
    return TestClient(app)


@pytest.mark.asyncio
async def test_get_questions(client, mock_question_service):
    """Test getting questions."""
    response = client.get("/api/v1/questions")
    assert response.status_code == 200
    data = response.json()
    assert len(data) == 1
    assert data[0]["id"] == "1"
    mock_question_service.get_questions.assert_called_once()


@pytest.mark.asyncio
async def test_submit_answers(client, mock_answer_service):
    """Test submitting answers."""
    payload = {"answers": [{"question_id": "1", "answer": "Python"}]}
    response = client.post("/api/v1/answers", json=payload)
    assert response.status_code == 201
    data = response.json()
    assert "message" in data
    mock_answer_service.submit_answers.assert_called_once()


@pytest.mark.asyncio
async def test_get_statistics(client, mock_answer_service):
    """Test getting statistics."""
    mock_answer_service.get_submitted_count.return_value = 10
    response = client.get("/api/v1/statistics")
    assert response.status_code == 200
    data = response.json()
    assert data == {"total_submitted": 10}
    mock_answer_service.get_submitted_count.assert_called_once()