// This file is auto-generated by AI agent
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import App from './App';

test('renders the landing page and navigates to questionnaire', async () => {
  const user = userEvent.setup();
  render(<App />);
  
  // Check landing page
  expect(screen.getByText('Otus Course Homework App')).toBeInTheDocument();
  expect(screen.getByRole('button', { name: /start questionnaire/i })).toBeInTheDocument();
  
  // Click button
  const button = screen.getByRole('button', { name: /start questionnaire/i });
  await user.click(button);
  
  // Check questionnaire appears
  expect(screen.getByText(/questionnaire/i)).toBeInTheDocument();
});