// This file is auto-generated by AI agent
import React, { useState } from 'react';
import { QuestionnaireForm } from './components/QuestionnaireForm';
import BugPage from './components/BugPage';
import StatisticsPage from './components/StatisticsPage';
import './App.css';

function App() {
  const [currentPage, setCurrentPage] = useState<'landing' | 'questionnaire' | 'bug' | 'statistics'>('landing');

  if (currentPage === 'questionnaire') {
    return (
      <div className="app">
        <QuestionnaireForm />
      </div>
    );
  }

  if (currentPage === 'bug') {
    return (
      <div className="app">
        <BugPage />
      </div>
    );
  }

  if (currentPage === 'statistics') {
    return (
      <div className="app">
        <StatisticsPage />
      </div>
    );
  }

  return (
    <div className="app">
      <div className="landing-page">
        <h1>Otus Course Homework App</h1>
        <button onClick={() => setCurrentPage('questionnaire')}>Start Questionnaire</button>
        <br />
        <button onClick={() => setCurrentPage('statistics')} style={{ marginTop: '1rem', backgroundColor: '#22c55e' }}>View Statistics</button>
        <br />
        <button onClick={() => setCurrentPage('bug')} style={{ marginTop: '1rem', backgroundColor: '#e53e3e' }}>Go to Bug Page</button>
      </div>
    </div>
  );
}

export default App;
