# This file is auto-generated by AI agent
"""Application services implementing business logic."""
from typing import List
from src.domain.models import Question, Answer
from src.domain.repositories import QuestionRepository, AnswerRepository


class QuestionService:
    """Service for managing questions."""
    
    def __init__(self, repository: QuestionRepository):
        self._repository = repository
    
    def get_questions(self) -> List[Question]:
        """Get all available questions."""
        return self._repository.get_all_questions()


class AnswerService:
    """Service for managing answers."""
    
    def __init__(self, repository: AnswerRepository):
        self._repository = repository
    
    def submit_answers(self, answers: List[Answer]) -> None:
        """Submit answers to the questionnaire."""
        if not answers:
            raise ValueError("Cannot submit empty answers")
        self._repository.save_answers(answers)
    
    def get_all_answers(self) -> List[Answer]:
        """Get all submitted answers."""
        return self._repository.get_all_answers()
    
    def get_submitted_count(self) -> int:
        """Get the total number of submitted questionnaires."""
        return self._repository.get_submitted_count()
    
    def no_tests_method(self) -> int:
        """A sample method without unit tests that returns the count of answers."""
        return len(self.get_all_answers())
